version: "3.6"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    image: nginx:alpine
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/demos.px.com/nuxt-app/demo/
      - ./.config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nuxt
